# GDB flash loader script
# Automatically generated by 'flashload.sh'
#    (modifications will be overwritten)
set $size = 763240
shell cp ./images/jffs2.img /tmp/flash.dat
writefile 0x00100000 $size
