# GDB flash loader script
# Automatically generated by 'flashload.sh'
#    (modifications will be overwritten)
set $size = 111540
shell cp /home/strubi/src/blackfin/u-boot_1.1.3/u-boot.bin /tmp/flash.dat
writefile 0x00000000 $size
