# GDB flash loader script
# Automatically generated by 'flashload.sh'
#    (modifications will be overwritten)
set $size = 1364548
shell cp /home/strubi/uClinux-dist/images/uImage /tmp/flash.dat
writefile 0x00100000 $size
