
// enum of possible errors
enum
{
	ERR_NONE,
	ERR_POLL_TIMEOUT = -1024, 
	ERR_VERIFY_WRITE,
	ERR_INVALID_SECTOR,
	ERR_INVALID_BLOCK,
	ERR_UNKNOWN_COMMAND,
	ERR_PROCESS_COMMAND,
	ERR_READ,
	ERR_DRV_NOT_AT_BREAK,
	ERR_BUFFER_IS_NULL,
	ERR_BUFSIZE_EXCESS,
	ERR_CHIP_UNSUPPORTED,
};

