
// enum of possible errors
enum
{
	NO_ERR,
	POLL_TIMEOUT,
	VERIFY_WRITE,
	INVALID_SECTOR,
	INVALID_BLOCK,
	UNKNOWN_COMMAND,
	PROCESS_COMMAND_ERR,
	NOT_READ_ERROR,
	DRV_NOTAT_BREAK,
	BUFFER_IS_NULL,
	BUFSIZE_EXCESS,
	CHIP_UNSUPPORTED,
	NUM_ERROR_CODES,   // always the last!
};

